### ISSUE TITLE
Garchmodels Roadmap

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [AlbertoAlmuinha/garchmodels#1]
# Garchmodels Project Roadmap

- [x] Create Package Structure
- [x] Develop Univariate Algorithm from rugarch package
- [x] Develop Multivariate Algorithm from rugarch package
- [x] Develop Multivariate Algorithms from rmgarch package
- [x] Create tests
- [x] Automate Tests with GitHub Actions
- [x] Make README
- [x] Make Getting Started Vignette
- [x] Pkgdown Documentation
- [x] Send to CRAN

# Future Work

- [x]  DIals Parameters for Tuning in Univariate Algorithms #2 
- [ ]  Engine Unification in Multivariate Algorithms #3 
- [ ] Support for Tuning Multivariate Models #4

# Models Roadmap

- [ ] Markov-Switching Models through MSGARGH 📦 

- [ ] Log Garch Models through the lgarch 📦
